
---
# Setup
- name: Cat bashrc
  ansible.builtin.command: cat $HOME/.bashrc
  become_user: opc
  register: bashrc_content
- name: Set SQLPATH to HOME
  ansible.builtin.shell: echo "export SQLPATH=$HOME" >> $HOME/.bashrc
  become_user: opc
  when: bashrc_content.stdout.find('SQLPATH') == -1

# Install Java and SQLcl
- name: Install JDK 22 headless
  ansible.builtin.package:
    name: jdk-22-headless
    update_cache: yes
- name: Install sqlcl
  ansible.builtin.package:
    name: sqlcl
    update_cache: yes

# SQLcl setup
- name: Copy login.sql file
  ansible.builtin.copy:
    src: ../files/login.sql
    dest: /home/opc/login.sql
    owner: opc
    group: opc
    mode: '0640'
- name: Copy highlight.json file
  ansible.builtin.copy:
    src: ../files/highlight.json
    dest: /home/opc/highlight.json
    owner: opc
    group: opc
    mode: '0640'

# Create directories
- name: Create conn directory
  ansible.builtin.file:
    path: /home/opc/conn
    state: directory
    owner: opc
    group: opc
    mode: '0744'
- name: Create init directory
  ansible.builtin.file:
    path: /home/opc/init
    state: directory
    owner: opc
    group: opc
    mode: '0744'
- name: Create queries directory
  ansible.builtin.file:
    path: /home/opc/queries
    state: directory
    owner: opc
    group: opc
    mode: '0744'

# Copy scripts
- name: Copy init SQL files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/opc/init/
    owner: opc
    group: opc
    mode: '0740'
  with_fileglob:
    - ../files/init/*.sql
- name: Copy demo CSV file
  ansible.builtin.copy:
    src: ../files/init/demo.csv
    dest: /home/opc/init/
    owner: opc
    group: opc
    mode: '0640'
- name: Copy queries SQL files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/opc/queries/
    owner: opc
    group: opc
    mode: '0640'
  with_fileglob:
    - ../files/queries/*.sql

# Connection ADMIN
- name: Copy conn/admin.sql template
  ansible.builtin.template:
    src: ../files/conn/admin.sql.j2
    dest: /home/opc/conn/admin.sql
    owner: opc
    group: opc
    mode: '0640'
- name: Create Admin connection
  ansible.builtin.command: "sql /nolog @/home/opc/conn/admin.sql"
  become_user: opc

# Create HOTEL user and connection
- name: Copy init/hotel.sql template
  ansible.builtin.template:
    src: ../files/init/hotel.sql.j2
    dest: /home/opc/init/hotel.sql
    owner: opc
    group: opc
    mode: '0640'
- name: Init Hotel
  ansible.builtin.command: "sql -name admin @/home/opc/init/hotel.sql"
  become_user: opc
- name: Copy conn/hotel.sql template
  ansible.builtin.template:
    src: ../files/conn/hotel.sql.j2
    dest: /home/opc/conn/hotel.sql
    owner: opc
    group: opc
    mode: '0640'
- name: Create Hotel connection
  ansible.builtin.command: "sql /nolog @/home/opc/conn/hotel.sql"
  become_user: opc

# Create OS Credentials
- name: Copy init/create_os_credentials.sql template
  ansible.builtin.template:
    src: ../files/init/create_os_credentials.sql.j2
    dest: /home/opc/init/create_os_credentials.sql
    owner: opc
    group: opc
    mode: '0640'
- name: Create Object Storage Credentials
  ansible.builtin.command: "sql -name hotel @/home/opc/init/create_os_credentials.sql"
  become_user: opc

# Import ONNX model
- name: Copy init/import_onnx.sql template
  ansible.builtin.template:
    src: ../files/init/import_onnx.sql.j2
    dest: /home/opc/init/import_onnx.sql
    owner: opc
    group: opc
    mode: '0640'
- name: Import ONNX model
  ansible.builtin.command: "sql -name hotel @/home/opc/init/import_onnx.sql"
  become_user: opc
- name: Select model
  ansible.builtin.command: "sql -name hotel @/home/opc/init/select_model.sql"
  become_user: opc
  register: select_model
- debug: msg="{{ select_model.stdout_lines }}"
- name: Model info
  ansible.builtin.command: "sql -name hotel @/home/opc/init/model_info.sql"
  become_user: opc
  register: model_info
- debug: msg="{{ model_info.stdout_lines }}"

# DML, triggers and DDL
- name: Create Hotel tables
  ansible.builtin.command: "sql -name hotel @/home/opc/init/ddl.sql"
  become_user: opc
- name: Create Trigger
  ansible.builtin.command: "sql -name hotel @/home/opc/init/trigger.sql"
  become_user: opc
- name: Insert Hotel data
  ansible.builtin.command: "sql -name hotel @/home/opc/init/dml.sql"
  become_user: opc