DROP TABLE IF EXISTS HOTELS;

CREATE TABLE IF NOT EXISTS HOTELS (
    ID NUMBER NOT NULL,
    NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(3000),
    DESCRIPTION_VECTOR VECTOR,
    CITY VARCHAR2(50),
    COUNTRY VARCHAR2(50),
    PRIMARY KEY (ID)
);

EXIT;