SELECT
    MODEL_NAME,
    ATTRIBUTE_NAME,
    ATTRIBUTE_TYPE,
    DATA_TYPE,
    VECTOR_INFO
FROM
    USER_MINING_MODEL_ATTRIBUTES
WHERE
    MODEL_NAME = 'DOC_MODEL'
ORDER BY
    ATTRIBUTE_NAME;

EXIT;