CREATE OR REPLACE FUNCTION FUNCTION_GET_HOTEL_DESCRIPTION_VECTOR_FROM_TEXT (
    P_TEXT IN HOTELS.DESCRIPTION%TYPE
) RETURN HOTELS.DESCRIPTION_VECTOR%TYPE AS
    V_VECTOR HOTELS.DESCRIPTION_VECTOR%TYPE;
BEGIN
    SELECT
        TO_VECTOR(VECTOR_EMBEDDING(DOC_MODEL USING P_TEXT AS DATA)) AS EMBEDDING INTO V_VECTOR;
    RETURN (V_VECTOR);
END FUNCTION_GET_HOTEL_DESCRIPTION_VECTOR_FROM_TEXT;
/

CREATE OR REPLACE TRIGGER TRIGGER_ADD_DESCRIPTION_VECTOR_FOR_HOTEL BEFORE
    INSERT OR UPDATE ON HOTELS FOR EACH ROW
BEGIN
    :NEW.DESCRIPTION_VECTOR := FUNCTION_GET_HOTEL_DESCRIPTION_VECTOR_FROM_TEXT(:NEW.DESCRIPTION);
END;
/

EXIT;