@$ORACLE_HOME/rdbms/admin/sqlsessstart.sql

set verify off

-- you must not change the owner of the functionality to avoid future issues
define username='C##CLOUD$SERVICE'

CREATE USER &USERNAME NO AUTHENTICATION ACCOUNT LOCK;

REM Grant Common User Privileges
GRANT INHERIT PRIVILEGES ON USER &USERNAME TO SYS;

GRANT INHERIT PRIVILEGES ON USER SYS TO &USERNAME;

GRANT RESOURCE, UNLIMITED TABLESPACE, SELECT_CATALOG_ROLE TO &USERNAME;

GRANT CREATE ANY TABLE, DROP ANY TABLE, INSERT ANY TABLE, SELECT ANY TABLE,
CREATE ANY CREDENTIAL, CREATE PUBLIC SYNONYM, CREATE PROCEDURE, ALTER SESSION, CREATE JOB TO &USERNAME;

GRANT CREATE SESSION, SET CONTAINER TO &USERNAME;

GRANT SELECT ON SYS.V_$MYSTAT TO &USERNAME;

GRANT SELECT ON SYS.SERVICE$ TO &USERNAME;

GRANT SELECT ON SYS.V_$ENCRYPTION_WALLET TO &USERNAME;

GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_PRIV_CAPTURE TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_PDB_LIB TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_CRYPTO TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_SYS_ERROR TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_ISCHED TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_PDB_LIB TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_PDB TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_SERVICE TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_PDB TO &USERNAME;

GRANT EXECUTE ON SYS.CONFIGURE_DV TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_SYS_ERROR TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_CREDENTIAL TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_RANDOM TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_SYS_SQL TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_LOCK TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_AQADM TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_AQ TO &USERNAME;

GRANT EXECUTE ON SYS.DBMS_SYSTEM TO &USERNAME;

GRANT EXECUTE ON SYS.SCHED$_LOG_ON_ERRORS_CLASS TO &USERNAME;

GRANT SELECT ON SYS.DBA_DATA_FILES TO &USERNAME;

GRANT SELECT ON SYS.DBA_EXTENTS TO &USERNAME;

GRANT SELECT ON SYS.DBA_CREDENTIALS TO &USERNAME;

GRANT SELECT ON SYS.AUDIT_UNIFIED_ENABLED_POLICIES TO &USERNAME;

GRANT SELECT ON SYS.DBA_ROLES TO &USERNAME;

GRANT SELECT ON SYS.V_$ENCRYPTION_KEYS TO &USERNAME;

GRANT SELECT ON SYS.DBA_DIRECTORIES TO &USERNAME;

GRANT SELECT ON SYS.DBA_USERS TO &USERNAME;

GRANT SELECT ON SYS.DBA_OBJECTS TO &USERNAME;

GRANT SELECT ON SYS.V_$PDBS TO &USERNAME;

GRANT SELECT ON SYS.V_$SESSION TO &USERNAME;

GRANT SELECT ON SYS.GV_$SESSION TO &USERNAME;

GRANT SELECT ON SYS.DBA_REGISTRY TO &USERNAME;

GRANT SELECT ON SYS.DBA_DV_STATUS TO &USERNAME;

ALTER SESSION SET CURRENT_SCHEMA=&USERNAME;

REM Create the Catalog objects
@$ORACLE_HOME/rdbms/admin/dbms_cloud_task_catalog.sql

@$ORACLE_HOME/rdbms/admin/dbms_cloud_task_views.sql

@$ORACLE_HOME/rdbms/admin/dbms_cloud_catalog.sql

@$ORACLE_HOME/rdbms/admin/dbms_cloud_types.sql

REM Create the Package Spec
@$ORACLE_HOME/rdbms/admin/prvt_cloud_core.plb

@$ORACLE_HOME/rdbms/admin/prvt_cloud_task.plb

@$ORACLE_HOME/rdbms/admin/dbms_cloud_capability.sql

@$ORACLE_HOME/rdbms/admin/prvt_cloud_request.plb

@$ORACLE_HOME/rdbms/admin/prvt_cloud_internal.plb

@$ORACLE_HOME/rdbms/admin/dbms_cloud.sql

@$ORACLE_HOME/rdbms/admin/prvt_cloud_admin_int.plb

REM Create the Package Body
@$ORACLE_HOME/rdbms/admin/prvt_cloud_core_body.plb

@$ORACLE_HOME/rdbms/admin/prvt_cloud_task_body.plb

@$ORACLE_HOME/rdbms/admin/prvt_cloud_capability_body.plb

@$ORACLE_HOME/rdbms/admin/prvt_cloud_request_body.plb

@$ORACLE_HOME/rdbms/admin/prvt_cloud_internal_body.plb

@$ORACLE_HOME/rdbms/admin/prvt_cloud_body.plb

@$ORACLE_HOME/rdbms/admin/prvt_cloud_admin_int_body.plb

-- Create the metadata
@$ORACLE_HOME/rdbms/admin/dbms_cloud_metadata.sql

ALTER SESSION SET CURRENT_SCHEMA=SYS;

@$ORACLE_HOME/rdbms/admin/sqlsessend.sql