SELECT
    ID,
    NAME,
    DESCRIPTION,
    CITY,
    COUNTRY
FROM
    HOTELS
ORDER BY
    VECTOR_DISTANCE( TO_VECTOR(VECTOR_EMBEDDING(DOC_MODEL USING '&1' AS DATA)), DESCRIPTION_VECTOR, EUCLIDEAN) FETCH FIRST &2 ROWS ONLY;

EXIT;