spring:
  application:
    name: vector
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@SERVICE_NAME_high?TNS_ADMIN=/Path/to/Wallet
    username: HOTEL
    password: "PASSWORD"
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      sql-for-validate-connection: SELECT * FROM dual
      connection-pool-name: connectionPoolName1
      initial-pool-size: 5
      min-pool-size: 5
      max-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      globally_quoted_identifiers: true
  oracle:
    jdbc:
      fanEnabled: true

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE