CREATE OR REPLACE PACKAGE VICTOR AS

    FUNCTION GET_A_NUMBER RETURN NUMBER;

    PROCEDURE DO_SOMETHING;
END VICTOR;
/

CREATE OR REPLACE PACKAGE BODY VICTOR AS

    FUNCTION GET_A_NUMBER RETURN NUMBER AS
        RETURN 1;
    END;

    PROCEDURE DO_SOMETHING
    BEGIN
        DBMS_OUTPUT .PUT_LINE('Hello World');
    END DO_SOMETHING;
END VICTOR;
/